<?xml version='1.0'?>
<robot name="car" xmlns:xacro="http://www.ros.org/wiki/xacro">
   <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
   <xacro:property name="car_width" value="1.46" />
   <xacro:property name="car_height" value="1.35" />
   <xacro:property name="car_length" value="1.94" />
   <xacro:property name="car_orientation" value="-1.646816" />

  	<link name="base_link">
		<visual>
        <origin xyz="0 0 0" rpy="0 0 ${car_orientation}" />
      <geometry>
        <mesh filename="package://inventacao_car_test/meshes/InventacaoCarModifiedToCamera.dae"/>
      </geometry>
    </visual>

    <!-- Required to maintain the 3d model above the ground (when dynamic model) -->
    <collision>
        <origin xyz="0 0 0" rpy="0 0 ${car_orientation}"/>
        <geometry>
          <mesh filename="package://inventacao_car_test/meshes/InventacaoCarModifiedToCamera.dae"/>
        </geometry>
      </collision>

    <!-- 3d model won't show up without inertial set-->
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 ${car_orientation}" />
        <inertia ixx="1.0" ixy="0" ixz="0"
                 iyy="1.0" iyz="0"
                 izz="1.0" />
        <mass value="100" />
      </inertial>
	</link>

  <!-- Camera -->
  <link name="camera_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <!--<origin xyz="${camera_link} 0 ${height3 - axel_offset*2}" rpy="0 0 0"/>-->
    <origin xyz="0 0 .4" rpy="0 1.57 3.14"/>
    <parent link="base_link"/>
    <child link="camera_link"/>
  </joint>

  <!-- Set model as kinematic -->
  <gazebo>
      <static>true</static>
  </gazebo>

   <!-- camera -->
  <gazebo reference="camera_link">
    <sensor type="camera" name="camera1">
      <update_rate>30.0</update_rate>
      <camera name="head">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>800</width>
          <height>800</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <!-- Noise is sampled independently per pixel on each frame.
               That pixel's noise value is added to each of its color
               channels, which at that point lie in the range [0,1]. -->
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>inventacao_car/camera1</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera_link</frameName>
        <hackBaseline>0.07</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
  </gazebo>

</robot>
